"""add music_info table

Revision ID: e62e1a9223da
Revises: 
Create Date: 2025-11-17 21:23:35.508004+08:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy.dialects.postgresql import ARRAY

# revision identifiers, used by Alembic.
revision: str = 'e62e1a9223da'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'music_info',
        sa.Column('id', sa.BigInteger(), nullable=False),
        sa.Column('uuid', sa.String(length=64), nullable=False),
        sa.Column('filepath', sa.String(length=255), nullable=True),
        sa.Column('album', sa.String(length=255), nullable=True),
        sa.Column('title', sa.String(length=255), nullable=True),
        sa.Column('artist', ARRAY(sa.Text()), nullable=True),
        sa.Column('date', sa.Integer(), nullable=True),
        sa.Column('lyrics', sa.Text(), nullable=True),
        sa.Column('album_artist', sa.String(length=255), nullable=True),
        sa.Column('time_length', sa.Integer(), nullable=True),
        sa.Column('search_vector', postgresql.TSVECTOR(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
    op.create_index(
        op.f('idx_music_info_search'),
        'music_info',
        ['search_vector'],
        unique=False,
        postgresql_using='gin'
    )

    op.execute(
        """
        CREATE OR REPLACE FUNCTION music_info_tsvector_update_custom()
        RETURNS trigger AS $$
        BEGIN
            NEW.search_vector :=
                setweight(to_tsvector('simple', coalesce(NEW.title, '')), 'A') ||
                setweight(to_tsvector('simple', coalesce(NEW.album, '')), 'B') ||
                setweight(to_tsvector('simple', coalesce(array_to_string(NEW.artist, ' '), '')), 'C') ||
                setweight(to_tsvector('simple', coalesce(NEW.lyrics, '')), 'D') ||
                setweight(to_tsvector('simple', coalesce(NEW.album_artist, '')), 'B');
            RETURN NEW;
        END
        $$ LANGUAGE plpgsql;
        """
    )

    # 创建触发器
    op.execute(
        """
        CREATE TRIGGER music_info_tsvector_update
            BEFORE INSERT OR UPDATE
            ON music_info
            FOR EACH ROW
        EXECUTE FUNCTION
            music_info_tsvector_update_custom()
        """
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.execute("DROP TRIGGER IF EXISTS music_info_tsvector_update ON music_info")
    op.execute("DROP FUNCTION IF EXISTS music_info_tsvector_update_custom()")
    op.drop_index(op.f('idx_music_info_search'), table_name='music_info', postgresql_using='gin')
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('music_info')
    # ### end Alembic commands ###
