"""alter music_info table

Revision ID: 4f7babbea05b
Revises: 1b8550e0f924
Create Date: 2025-11-26 22:59:32.978314+08:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4f7babbea05b'
down_revision: Union[str, Sequence[str], None] = '1b8550e0f924'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('music_info', sa.Column('pictures', postgresql.ARRAY(sa.Text(), zero_indexes=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('music_info', 'pictures')
    # ### end Alembic commands ###
